changelog:
  categories:
    - title: Added
      labels:
        - enhancement
    - title: Changed
      labels:
        - bug
        - documentation
    - title: Other
      labels:
        - "*"
